IMPORTAMOS EL ARCHIVO

In [38]:
import pandas as pd
import glob
import datetime as dt
import os
from dotenv import load_dotenv

# Cargar variables desde el archivo .env
load_dotenv()

# Obtener la zona horaria (y usar 'UTC' por defecto si no existe la variable)
user_tz = os.getenv('USER_TIMEZONE', 'UTC')

# 1. Localizar el único archivo CSV en la carpeta raw
# glob.glob devuelve una lista con los nombres de archivos que coinciden
archivos = glob.glob('../data/raw/*.csv')

# 2. Abrir el archivo (tomamos el primero de la lista [0])
if archivos:
    ruta_archivo = archivos[0]
    print(f"Archivo detectado y cargado: {ruta_archivo}")
    df = pd.read_csv(ruta_archivo)
    
    # Mostrar las primeras filas para confirmar
    display(df.head())
    display(df.info())

else:
    print("Error: No se encontró ningún archivo CSV en data/raw/")

Archivo detectado y cargado: ../data/raw\BODY_1773136878051.csv

,time,weight,height,bmi,fatRate,bodyWaterRate,boneMass,metabolism,muscleRate,visceralFat
0,2023-03-28 20:29:16+0000,100.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023-03-28 20:29:58+0000,99.95,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2023-03-28 20:30:18+0000,100.10,192.0,27.1,29.087900,50.631240,3.622399,1836.0,67.36061,13.0
3,2023-03-29 19:11:20+0000,101.20,192.0,27.4,29.383190,50.420403,3.647219,1852.0,67.81699,13.0
4,2023-03-30 19:25:15+0000,100.80,192.0,27.3,29.290665,50.486465,3.637460,1846.0,67.63755,13.0

<class 'pandas.DataFrame'>
RangeIndex: 161 entries, 0 to 160
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   time           161 non-null    str
 1   weight         161 non-null    float64
 2   height         159 non-null    float64
 3   bmi            159 non-null    float64
 4   fatRate        135 non-null    float64
 5   bodyWaterRate  135 non-null    float64
 6   boneMass       135 non-null    float64
 7   metabolism     135 non-null    float64
 8   muscleRate     135 non-null    float64
 9   visceralFat    135 non-null    float64
dtypes: float64(9), str(1)
memory usage: 12.7 KB

None

ELIMNAMOS FILAS CON NULOS

In [39]:
#Eliminamos filas con nulos.
df_clean = df.dropna()
df_clean.isnull().sum()

display (df_clean)
display (df_clean.info())

,time,weight,height,bmi,fatRate,bodyWaterRate,boneMass,metabolism,muscleRate,visceralFat
2,2023-03-28 20:30:18+0000,100.10,192.0,27.100000,29.087900,50.631240,3.622399,1836.0,67.360610,13.0
3,2023-03-29 19:11:20+0000,101.20,192.0,27.400000,29.383190,50.420403,3.647219,1852.0,67.816990,13.0
4,2023-03-30 19:25:15+0000,100.80,192.0,27.300000,29.290665,50.486465,3.637460,1846.0,67.637550,13.0
5,2023-04-01 19:00:20+0000,99.85,192.0,27.000000,29.147108,50.588963,3.610205,1832.0,67.136406,13.0
6,2023-04-03 19:19:26+0000,100.10,192.0,27.100000,28.945244,50.733097,3.629764,1836.0,67.496050,13.0
...,...,...,...,...,...,...,...,...,...,...
152,2025-07-21 17:42:06+0000,93.05,192.0,25.241428,26.490050,50.427826,3.489219,1713.0,64.911800,13.0
153,2025-07-24 10:49:16+0000,93.10,192.0,25.254992,26.512340,50.412537,3.490044,1714.0,64.926960,13.0
154,2025-07-30 10:21:50+0000,92.65,192.0,25.132921,26.310837,50.550766,3.482617,1707.0,64.790400,13.0
155,2025-08-05 09:35:33+0000,93.10,192.0,25.254992,26.512340,50.412537,3.490044,1714.0,64.926960,13.0
160,2026-03-10 09:46:42+0000,98.85,192.0,26.814780,29.014858,50.683390,3.580402,1790.0,66.588410,14.0

<class 'pandas.DataFrame'>
Index: 135 entries, 2 to 160
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   time           135 non-null    str
 1   weight         135 non-null    float64
 2   height         135 non-null    float64
 3   bmi            135 non-null    float64
 4   fatRate        135 non-null    float64
 5   bodyWaterRate  135 non-null    float64
 6   boneMass       135 non-null    float64
 7   metabolism     135 non-null    float64
 8   muscleRate     135 non-null    float64
 9   visceralFat    135 non-null    float64
dtypes: float64(9), str(1)
memory usage: 11.6 KB

None

Redondeamos los campos numericos a dos digfitos.

In [40]:
# Aplicamos redondeos
cols_refact = ['bmi', 'fatRate', 'bodyWaterRate', 'boneMass', 'muscleRate']
df_clean [cols_refact] = df_clean[cols_refact].round(2)

display (df_clean)
display (df_clean.info())

,time,weight,height,bmi,fatRate,bodyWaterRate,boneMass,metabolism,muscleRate,visceralFat
2,2023-03-28 20:30:18+0000,100.10,192.0,27.10,29.09,50.63,3.62,1836.0,67.36,13.0
3,2023-03-29 19:11:20+0000,101.20,192.0,27.40,29.38,50.42,3.65,1852.0,67.82,13.0
4,2023-03-30 19:25:15+0000,100.80,192.0,27.30,29.29,50.49,3.64,1846.0,67.64,13.0
5,2023-04-01 19:00:20+0000,99.85,192.0,27.00,29.15,50.59,3.61,1832.0,67.14,13.0
6,2023-04-03 19:19:26+0000,100.10,192.0,27.10,28.95,50.73,3.63,1836.0,67.50,13.0
...,...,...,...,...,...,...,...,...,...,...
152,2025-07-21 17:42:06+0000,93.05,192.0,25.24,26.49,50.43,3.49,1713.0,64.91,13.0
153,2025-07-24 10:49:16+0000,93.10,192.0,25.25,26.51,50.41,3.49,1714.0,64.93,13.0
154,2025-07-30 10:21:50+0000,92.65,192.0,25.13,26.31,50.55,3.48,1707.0,64.79,13.0
155,2025-08-05 09:35:33+0000,93.10,192.0,25.25,26.51,50.41,3.49,1714.0,64.93,13.0
160,2026-03-10 09:46:42+0000,98.85,192.0,26.81,29.01,50.68,3.58,1790.0,66.59,14.0

<class 'pandas.DataFrame'>
Index: 135 entries, 2 to 160
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   time           135 non-null    str
 1   weight         135 non-null    float64
 2   height         135 non-null    float64
 3   bmi            135 non-null    float64
 4   fatRate        135 non-null    float64
 5   bodyWaterRate  135 non-null    float64
 6   boneMass       135 non-null    float64
 7   metabolism     135 non-null    float64
 8   muscleRate     135 non-null    float64
 9   visceralFat    135 non-null    float64
dtypes: float64(9), str(1)
memory usage: 11.6 KB

None

CAMBIAMOS LA COLUMNA TIME A DATETIME

In [41]:
#Cambiamos a datetme

df_clean ['time'] = pd.to_datetime (df_clean['time'])
df_clean['time'] = df_clean['time'].dt.tz_convert(user_tz).dt.tz_localize(None)

print(df_clean['time'].head())
display (df_clean)
display (df_clean.info())

2   2023-03-28 22:30:18
3   2023-03-29 21:11:20
4   2023-03-30 21:25:15
5   2023-04-01 21:00:20
6   2023-04-03 21:19:26
Name: time, dtype: datetime64[us]

,time,weight,height,bmi,fatRate,bodyWaterRate,boneMass,metabolism,muscleRate,visceralFat
2,2023-03-28 22:30:18,100.10,192.0,27.10,29.09,50.63,3.62,1836.0,67.36,13.0
3,2023-03-29 21:11:20,101.20,192.0,27.40,29.38,50.42,3.65,1852.0,67.82,13.0
4,2023-03-30 21:25:15,100.80,192.0,27.30,29.29,50.49,3.64,1846.0,67.64,13.0
5,2023-04-01 21:00:20,99.85,192.0,27.00,29.15,50.59,3.61,1832.0,67.14,13.0
6,2023-04-03 21:19:26,100.10,192.0,27.10,28.95,50.73,3.63,1836.0,67.50,13.0
...,...,...,...,...,...,...,...,...,...,...
152,2025-07-21 19:42:06,93.05,192.0,25.24,26.49,50.43,3.49,1713.0,64.91,13.0
153,2025-07-24 12:49:16,93.10,192.0,25.25,26.51,50.41,3.49,1714.0,64.93,13.0
154,2025-07-30 12:21:50,92.65,192.0,25.13,26.31,50.55,3.48,1707.0,64.79,13.0
155,2025-08-05 11:35:33,93.10,192.0,25.25,26.51,50.41,3.49,1714.0,64.93,13.0
160,2026-03-10 10:46:42,98.85,192.0,26.81,29.01,50.68,3.58,1790.0,66.59,14.0

<class 'pandas.DataFrame'>
Index: 135 entries, 2 to 160
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   time           135 non-null    datetime64[us]
 1   weight         135 non-null    float64
 2   height         135 non-null    float64
 3   bmi            135 non-null    float64
 4   fatRate        135 non-null    float64
 5   bodyWaterRate  135 non-null    float64
 6   boneMass       135 non-null    float64
 7   metabolism     135 non-null    float64
 8   muscleRate     135 non-null    float64
 9   visceralFat    135 non-null    float64
dtypes: datetime64[us](1), float64(9)
memory usage: 11.6 KB

None